### ISSUE TITLE
Fatal error when generating README

### ISSUE THREAD

**Issue by XhmikosR** [gruntjs/grunt-contrib-internal#28]
So this happens if the changelog has a line which begins with a backtick
Example:

```yml
v0.10.0:
  date: 2014-02-07
  changes:
    - `sourceMappingURL` calculated correctly.
```

```
Running "build-contrib" task
Fatal error: Unable to parse "CHANGELOG" file (undefined).
```

**Comment by XhmikosR** [comment]
OK, it's due to `grunt.file.readYAML`. A backtick cannot start the line as per the YAML specs.

Shouldn't we use markdown instead of yaml?

**Comment by XhmikosR** [comment]
As a workaround I found that it works if I wrap the whole thing into double quotes, like

```yml
v0.10.0:
  date: 2014-02-07
  changes:
    - "`sourceMappingURL` calculated correctly."
```
